### ISSUE TITLE
Extension for VB.NET

### ISSUE THREAD

**Issue by flashback2k14** [tleish/redmine_jstoolbar_ext_coderay#1]
Hey,
thanks for your great Plugin for Redmine. It works very well. It's possible to implement VB.NET. I can't figure out, how to implemet this for my self. That's would be really nice, if you could help me. 
THANKS!!!!!!

**Comment by tleish** [comment]
This plugin only supports inserting markup to support syntax highlighting.  Be default redmine uses Coderay (http://coderay.rubychan.de/), which does not have syntax highlighting for VB.NET.  Others have installed other syntax highlighters like Pygmentize, which I am not familiar with.  If you can get something installed to support VB.NET parsing, I can help you get a button setup for inserting the necessary markup.
