### ISSUE TITLE
bash/perl support

### ISSUE THREAD

**Issue by mauro-miatello** [tleish/redmine_jstoolbar_ext_coderay#3]
please add highlight for bash and/or perl
thanks

**Comment by tleish** [comment]
Redmine uses [CodeRay](http://coderay.rubychan.de/) for code syntax highlighting.  CodeRay does not currently support bash and/or perl.  I am not the author of CodeRay.  Until it's available in CodeRay, it cannot be added to this toolbar.  I suggest adding your feedback to https://github.com/rubychan/coderay/issues.
